# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Minutes Title')),
            ],
        ),
        migrations.DeleteModel(
            name='Minute',
        ),
    ]
