# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170411_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='minutes_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Minutes URL'),
        ),
    ]
